config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  post 'search', to: 'members#search'
  get 'search', to:'members#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'members#new'
  resources :members, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :goods
    end
  end
  resources :tweets, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :member
  belongs_to :tweet
end

app/models/member.rb
class Member < ApplicationRecord
  before_save { self.email.downcase!}
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tweets
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :member
  has_many :likes
  has_many :likeposts, through: :likes, source: :tweet
  
  def follow(other_member)
    unless self == other_member
     self.relationships.find_or_create_by(follow_id: other_member.id)
    end
  end
  
  def unfollow(other_member)
    relationship = self.relationships.find_by(follow_id: other_member.id)
    relationship.destroy if relationship
  end
  
  def following?(other_member)
    self.followings.include?(other_member)
  end
  
  def feed_tweets
    Tweet.where(member_id: self.following_ids + [self.id])
  end
  
  def good(tweet)
    likes.find_or_create_by(tweet_id: tweet.id)
  end
  
  def bad(tweet)
    like = likes.find_by(tweet_id: tweet.id)
    like.destroy if like
  end
  
  def likepost?(tweet)
    self.likeposts.include?(tweet)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :member
  belongs_to :follow, class_name: 'Member'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :member
  
  validates :content, presence: true, length: { maximum: 200}
  
  has_many :likes, foreign_key: 'tweet_id', dependent: :destroy
  has_many :members, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_member_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(member)
    @count_tweets = member.tweets.count
    @count_followings = member.followings.count
    @count_followers = member.followers.count
    @count_likes = member.likes.count
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_member_logged_in
  def create
    tweet = Tweet.find(params[:tweet_id])
    current_member.good(tweet)
    flash[:success] = 'お気に入り登録しました^^'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    current_member.bad(tweet)
    flash[:success] = 'お気に入り解除しました><'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :require_member_logged_in, only: [:index, :show, :followings, :followers, :likes]
  
  def index
    @members = Member.order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @member = Member.find(params[:id])
    @tweets = @member.tweets.order(id: :desc).page(params[:page])
    counts(@member)
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    
    if @member.save
      flash[:success] = 'メンバー登録完了です^^'
      redirect_to @member
    else
      flash[:danger] = 'メンバー登録、失敗です><'
      render :new
    end
  end
  
  def followings
    @member = Member.find(params[:id])
    @followings = @member.followings.page(params[:page])
    counts(@member)
  end
  
  def followers
    @member = Member.find(params[:id])
    @followers = @member.followers.page(params[:page])
    counts(@member)
  end
  
  def goods
    @member = Member.find(params[:id])
    @likeposts = @member.likeposts.page(params[:page])
    counts(@member)
  end
  
  def search
    if params[:member][:search] == nil || params[:member][:search] == ""
        flash[:danger] = "フォローメンバーを入力して下さい！"
        redirect_back(fallback_location: root_path)
      else
        @members = current_member.followings.where('name LIKE ?', "%#{params[:member][:search]}%")
      end
      @tweet = Tweet.where(member_id:  @members)
  end
  
  private

  def member_params
    params.require(:member).permit(:name,:email,:password,:password_confirmation,:search)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    member = Member.find(params[:follow_id])
    current_member.follow(member)
    flash[:success] = 'メンバーをフォローしました^^'
    redirect_to member
  end

  def destroy
    member = Member.find(params[:follow_id])
    current_member.unfollow(member)
    flash[:success] = 'メンバーのフォローを解除しました><'
    redirect_to member
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログイン成功です^^'
      redirect_to @member
    else
      flash.now[:danger] = 'ログイン失敗です><'
      render :new
    end
  end

  def destroy
    session[:member_id] = nil
    flash[:success] = 'ログアウトしました〜〜〜'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @member = Member.find_by(email: email)
    if @member && @member.authenticate(password)
      session[:member_id] =@member.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @tweet = current_member.tweets.build
      @tweets = current_member.feed_tweets.order(id: :desc).page(params[:page]).per(10)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_member_logged_in
  before_action :correct_member, only: [:destroy]
  
  def create
    @tweet = current_member.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = 'Tweetしました！'
      redirect_to root_url
    else
      @tweets = current_member.feed_tweets.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'Tweet出来ません! 1~200文字以内で投稿して下さい！><'
      render 'toppages/index'
    end
  end

  def destroy
    @tweet.destroy
    flash[:success] = 'Tweetを削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def tweet_params
    params.require(:tweet).permit(:content)
  end
  
  def correct_member
    @tweet = current_member.tweets.find_by(id: params[:id])
    unless @tweet
     redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_url(member, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(member.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end
  
  def logged_in?
    !!current_member
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">LikePost</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'お気に入り一覧', goods_member_path(current_member), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'メンバー', members_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_member.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to '個人詳細', member_path(current_member) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>LikePost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_good_button.html.erb
<% if current_member.likepost?(tweet) %>
 <%= form_with(model: current_member.likes.find_by(tweet_id: tweet.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :tweet_id, tweet.id %>
    <%= f.submit 'お気に入り登録解除', class: 'btn btn-danger' %>
  <% end %>
<% else %>
   <%= form_with(model: current_member.likes.build, local: true) do |f| %>
    <%= hidden_field_tag :tweet_id, tweet.id %>
    <%= f.submit 'お気に入り登録', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/members/_members.html.erb
<% if members.any? %>
  <ul class="list-unstyled">
    <% members.each do |member| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(member, { size: 40 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= member.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', member_path(member) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate members %>
<% end %>

app/views/members/followers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @member.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@member, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', member: @member %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= member_path(@member) %>" class="nav-link <%= 'active' if current_page?(member_path(@member)) %>">ツイート<span class="badge badge-secondary"><%= @count_tweets %></span></a></li>
      <li class="nav-item"><a href="<%= followings_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(followings_member_path(@member)) %>">フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(followers_member_path(@member)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= goods_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(goods_member_path(@member)) %>">お気に入り  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'members', members: @followers %>
  </div>
</div>

app/views/members/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @member.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@member, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', member: @member %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= member_path(@member) %>" class="nav-link <%= 'active' if current_page?(member_path(@member)) %>">ツイート<span class="badge badge-secondary"><%= @count_tweets %></span></a></li>
      <li class="nav-item"><a href="<%= followings_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(followings_member_path(@member)) %>">フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(followers_member_path(@member)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= goods_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(goods_member_path(@member)) %>">お気に入り  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'members', members: @followings %>
  </div>
</div>

app/views/members/goods.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @member.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@member, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', member: @member %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= member_path(@member) %>" class="nav-link <%= 'active' if current_page?(member_path(@member)) %>">ツイート<span class="badge badge-secondary"><%= @count_tweets %></span></a></li>
      <li class="nav-item"><a href="<%= followings_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(followings_member_path(@member)) %>">フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(followers_member_path(@member)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= goods_member_path(@member) %>" class="nav-link <%= 'active' if current_page?(goods_member_path(@member)) %>">お気に入り  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'tweets/tweets', tweets: @likeposts %>
  </div>
</div>

app/views/members/index.html.erb
<%= render 'members', members: @members %>

app/views/members/new.html.erb
<div class="text-center">
  <h1>新規登録お願いします！</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @member, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メール' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/members/search.html.erb
<ul class="list-unstyled">
  <% @tweet.each do |tweet| %>
   <li class="media mb-3">
     <img class="mr-2 rounded" src="<%= gravatar_url(tweet.member, {size: 50}) %>" alt="">
     <div class="media-body">
       <div>
         <%= link_to tweet.member.name, member_path(tweet.member) %> <span class="text-muted">posted at <%= tweet.created_at %></span>
       </div>
       <div>
         <p><%= tweet.content %></p>
       </div>
       <div>
          <% if current_member == tweet.member %>
            <%= link_to "削除", tweet, method: :delete, data: { confirm: "ホンマに削除してええん?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
          <!--お気に入りボタン登録-->
        <div>
          <%= render 'likes/good_button', tweet: tweet %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/members/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @member.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@member, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= member_path(@member) %>" class="nav-link <%= 'active' if current_page?(member_path(@member)) %>">ツイート<span class="badge badge-secondary"><%= @count_tweets %></span></a></li>
      <li class="nav-item"><a href="#" class="nav-link">フォロー</a></li>
      <li class="nav-item"><a href="#" class="nav-link">フォロワー</a></li>
    </ul>
    <%= render 'tweets/tweets', tweets: @tweets %>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_member == member %>
 <% if current_member.following?(member) %>
  <%= form_with(model: current_member.relationships.find_by(follow_id: member.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :follow_id, member.id %>
    <%= f.submit 'フォロー解除', class:'btn btn-danger btn-block' %>
  <% end %>
 <% else %>
  <%= form_with(model: current_member.relationships.build, local: true) do |f| %>
   <%= hidden_field_tag :follow_id, member.id %>
   <%= f.submit 'フォローする', class:'btn btn-primary btn-block' %>
  <% end %>
 <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-sm-4">
      <%= form_with(model: @tweet, local: true) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Tweet', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      <%= render 'tweets/tweets', tweets: @tweets %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>LikePostを始めよう！</h1>
    <%= link_to 'まずは登録からどうぞ !', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>
<% end %>

app/views/tweets/_tweets.html.erb
<%= form_with(url: search_path,scope: :member, local: true) do |f| %>
     <%= f.label :search, '検索' %>
     <h3>※フォローしてるメンバーの名前を検索して下さい！</h3><br>
     <p>※フォローメンバーとフォローメンバーのツイート一覧が表示されます</p><br>
     <p>※フォローメンバーがツイートしてなかったら表示されません。</p>
     <%= f.text_field :search, class: "form-control mr-sm-2", placeholder: 'following_member_name' %>
     <%= f.submit 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

<ul class="list-unstyled">
  <% tweets.each do |tweet| %>
   <li class="media mb-3">
     <img class="mr-2 rounded" src="<%= gravatar_url(tweet.member, {size: 50}) %>" alt="">
     <div class="media-body">
       <div>
         <%= link_to tweet.member.name, member_path(tweet.member) %> <span class="text-muted">posted at <%= tweet.created_at %></span>
       </div>
       <div>
         <p><%= tweet.content %></p>
       </div>
       <div>
          <% if current_member == tweet.member %>
            <%= link_to "削除", tweet, method: :delete, data: { confirm: "ホンマに削除してええん?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
          <!--お気に入りボタン登録-->
        <div>
          <%= render 'likes/good_button', tweet: tweet %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tweets %>
</ul>